### ISSUE TITLE
Stopwatch game doesn't trigger end_game(true)

### ISSUE THREAD

**Issue by gerazov** [NStefan002/speedtyper.nvim#19]
The `stopwatch.util.update_extmarks()` doesn't trigger the `eng_game(true)`. The game ends with `end_game(false)`.

**Comment by NStefan002** [comment]
I just tested it, it triggers `end_game(true)`. If it didn't trigger `end_game(true)`, the game wouldn't show statistics at the end of the round. `end_game(false)` is triggered when exiting the game buffer (will rework that one, but currently it does the job). Let me know if I misunderstood something.

**Comment by gerazov** [comment]
Hmm, maybe it was some quirk - closing this :+1:
