### ISSUE TITLE
Choosing text for typing

### ISSUE THREAD

**Issue by paranormal** [NStefan002/speedtyper.nvim#3]
## Describe the problem

Any plans on having a text for typing configurable? Or maybe turning it into real typing tutor?

## Describe the solution

I decompiled (freed or stole if you will) lessons from [Solo On Keyboard Dvorak Edition](https://gist.github.com/paranormal/68571263c9d034bd256a108af8294040) and I think we could use it. This is the intellectual property of russians, and they abandoned the blob moving to web version a while ago. Besides, hence they bomb city I live right now I don't see how complain from them merits a response.

**Comment by NStefan002** [comment]
First of all, I'm sorry to hear about the situation you're facing. Hope you're doing ok.

As far as your suggestion goes, I didn't understand very clearly the `turning it into a real typing tutor` part. Can you provide more explanation?

>Any plans on having a text for typing configurable? 

I could add an option for users to specify a path to the file that contains custom text. 
Also, maybe I should add an option `randomize_user_text` or something like that which would determine if the user's text is displayed in the same order as it is in the file or randomized. With that, I would probably need to add some other things to make it customizable `enough`.

**Comment by paranormal** [comment]
Don't be sorry. It's ridiculous how everyone who has nothing to do with the cause is sorry. Moving on.

Yes, take a look at [gtypist](https://www.gnu.org/savannah-checkouts/gnu/gtypist/gtypist.html), [ktouch](https://apps.kde.org/ktouch). Apart from timers/statistic the main feature of any typing tutor is the ability to choose what to type. Some tutors have deliberately created text, if you follow it you first learn home row, etc, then intertwined with some other.

If you ever consider adding this functionality keep in mind that you can take lessons for drorak us keyboard from link I provided, and embed it in your plugin.

**Comment by NStefan002** [comment]
Thanks for the suggestions and links. For now, tutor functionality is not my main goal (mainly because of my lack of time), but I will for sure consider it in the future. For now, I plan to add an option for users to specify their own text, to somewhat simulate the specialized tests that the tools you linked provide. 

In the meantime, if someone, including you, @paranormal, wants to take on this challenge just for fun, that would be really nice.

**Comment by NStefan002** [comment]
> For now, I plan to add an option for users to specify their own text, to somewhat simulate the specialized tests that the tools you linked provide.

See #4. I tested it but I would like to hear some feedback.

**Comment by paranormal** [comment]
with this lazy config: 

  ```
 return {
	"NStefan002/speedtyper.nvim",
	cmd = "Speedtyper",
	opts = {
		custom_text_file = "/home/user/solo_dvorak.txt"
	},
}
```


I've got this error


```
Error executing vim.schedule lua callback: ...dtyper.nvim/lua/speedtyper/game_modes/countdown/util.lua:14: attempt to get length of upvalue 'words' (a boolean value)
stack traceback:
	...dtyper.nvim/lua/speedtyper/game_modes/countdown/util.lua:14: in function 'new_word'
	...dtyper.nvim/lua/speedtyper/game_modes/countdown/util.lua:28: in function 'generate_sentence'
	...dtyper.nvim/lua/speedtyper/game_modes/countdown/util.lua:44: in function 'generate_extmarks'
	...dtyper.nvim/lua/speedtyper/game_modes/countdown/init.lua:23: in function 'start_game'
	.../share/nvim/lazy/speedtyper.nvim/lua/speedtyper/menu.lua:34: in function 'on_choice'
	...are/nvim/lazy/dressing.nvim/lua/dressing/select/init.lua:78: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

But if the lesson file is in the `~/.config/nvim` directory it is found and everything works. Now looking at problem from another angle: are you sure you want to allow people to have their files? Now you need to think about some kind of interface, making it work with ktouch format, etc. Take a look at [ktouch manual](https://sodilinux.itd.cnr.it/sdl6x3/documentazione/ktouch/ktouch.pdf) for features.

**Comment by NStefan002** [comment]
I get that error only if I provide an incorrect path to the file. With that, Speedtyper should also notify you of an error: `Failed to read from the file: /some/wrong/path`. It shouldn't have to do anything with the `~/.config/nvim` directory.
