### ISSUE TITLE
request for feature

### ISSUE THREAD

**Issue by vijha742** [NStefan002/speedtyper.nvim#46]
## Feature

Typing Speed Calculation in every document I am typing
## Describe the solution

In a opened file whenever I enter insert mode and whenever I exit between this interval a speed counter widget to tell me my speed.

P.s. Forgive me if request is silly or already available, as I didn't due research before

**Comment by NStefan002** [comment]
Hi, thanks for the suggestion! I like the idea, but I will 100% not add it to the current version of speedtyper. The main reason is that I'm currently working on version 2 and don't want to lose time on v1. 
But, I may add this to the v2 just for fun. Until then, check out [vim-apm](https://github.com/ThePrimeagen/vim-apm/tree/master) by theprimeagen (I don't know the state of it or if it is working at all), it seems to be just the right thing for you
