### ISSUE TITLE
Error when closing window

### ISSUE THREAD

**Issue by gerazov** [NStefan002/speedtyper.nvim#6]
Awesome plugin :sunglasses: 

After finishing the countdown game  when I quit the results window with `:q` it closes with the following error:
```lua
"lua/plugins/speedtyper.lua" 46L, 1731B written
Error detected while processing BufLeave Autocommands for "*":
Error executing lua callback: ...dtyper.nvim/lua/speedtyper/game_modes/countdown/init.lua:48: handle 0x55b742f94050 is already closing
stack traceback:
	[C]: in function 'close'
	...dtyper.nvim/lua/speedtyper/game_modes/countdown/init.lua:48: in function 'stop'
	.../lazy/speedtyper.nvim/lua/speedtyper/game_modes/init.lua:37: in function 'end_game'
	.../lazy/speedtyper.nvim/lua/speedtyper/game_modes/init.lua:25: in function <.../lazy/speedtyper.nvim/lua/speedtyper/game_modes/init.lua:24>
```
And the cursor remains hidden in the original window.

- Neovim version: 0.9.4

**Comment by NStefan002** [comment]
Hi! Thanks for reporting this. It should be fixed now. Do you mind trying it out?

**Comment by gerazov** [comment]
Fixed thanks :pray: 

I still don't get the cursor back in the original window, i.e. it remains hidden - should I open another issue?

**Comment by NStefan002** [comment]
Sorry, I haven't experienced the cursor disappearing bug (neither when using version 0.9.4 nor nightly). Do you mind sharing more information (e.g. your speedtyper config, or screen recording)? Thanks!

**Comment by gerazov** [comment]
The cursor issue has disappeared - :+1:
