### ISSUE TITLE
Countdown game word list size doesn't increase if float window height is increased

### ISSUE THREAD

**Issue by gerazov** [NStefan002/speedtyper.nvim#8]
When I double the window height from 5 to 10 the word list size in the Countdown game doesn't increase to fill the new window - it remains at the 5 row height.

**Comment by NStefan002** [comment]
A decent amount of parts of this game were originally very poorly written (including the issue you mentioned, the number of lines is hard-coded). I'm currently working on a rewrite so I will not solve this issue in this version of Speedtyper. But expect it to be solved very soon when the new version drops.
